# Generated by Django 3.2.5 on 2021-08-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tim',
            options={'ordering': ['-created_at']},
        ),
    ]
