# Generated by Django 3.2.5 on 2021-08-10 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tims', '0003_auto_20210810_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tim',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tim_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
