# Generated by Django 3.2.5 on 2021-08-12 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tims', '0004_auto_20210810_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tim',
            name='co_host',
        ),
        migrations.AddField(
            model_name='tim',
            name='co_host',
            field=models.ManyToManyField(blank=True, related_name='co_host', to=settings.AUTH_USER_MODEL),
        ),
    ]
